---

- hosts: all
  tasks:
    - name: Install Packages
      package:
        name:
          - caddy
          - tmux
          - nano
          - wget
          - htop
        state: latest
        update_cache: yes