---

- hosts: all
  pre_tasks:
    - name: Update package cache
      tags: always
      package:
        update_cache: yes
  tasks:
    - name: Install Packages
      tags: always
      package:
        name:
          - tmux
          - nano
          - wget
          - htop
          - unzip
        state: latest

- hosts: prod
  tasks:
    - name: Install Prod Packages
      tags: prod,caddy
      package:
        name:
          - caddy
        state: latest
    - name: Start caddy service
      tags: prod,caddy
      service:
        name: caddy
        state: started
        enabled: yes
      when: ansible_os_family == 'RedHat'
    - name: Install Firewall (Debian)
      tags: prod,firewall,debian
      apt:
        name:
          - ufw
        state: latest
      when: ansible_os_family == 'Debian'
    - name: Install Firewall (RHEL)
      tags: prod,firewall,rhel
      dnf:
        name:
          - firewalld
        state: latest
      when: ansible_os_family == 'RedHat'
    - name: Copy Login Message
      tags: prod,info
      copy:
        src: login-info.sh
        dest: /etc/profile.d/login-info.sh
        owner: root
        group: root
        mode: 0755
    - name: Install Terraform
      tags: prod,terraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/1.10.2/terraform_1.10.2_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        mode: 0755
        owner: root
        group: root
        