---

- hosts: all
  pre_tasks:
    - name: Update package cache
      package:
        update_cache: yes
  tasks:
    - name: Install Packages
      package:
        name:
          - tmux
          - nano
          - wget
          - htop
        state: latest

- hosts: prod
  tasks:
    - name: Install Prod Packages
      package:
        name:
          - caddy
        state: latest