---

- hosts: all
  tasks:
    - name: Install Packages
      apt:
        name:
          - caddy
          - tmux
          - nano
          - wget
          - htop
        state: latest
        update_cache: yes
      when: ansible_os_family == 'Debian'
      dnf:
        name:
          - caddy
          - tmux
          - nano
          - wget
          - htop
        state: latest
        update_cache: yes
      when: ansible_os_family == 'RedHat'